name: Security Agent - Terraform Plan

on:
  pull_request:
    branches: [main]
    paths:
      - 'security-agent/**'
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0
          
      - name: Terraform Format Check
        run: |
          terraform fmt -check -recursive security-agent/terraform/
          
      - name: Terraform Init
        run: |
          cd security-agent/terraform
          terraform init -backend=false
          
      - name: Terraform Validate
        run: |
          cd security-agent/terraform
          terraform validate
          
      - name: Terraform Plan
        id: plan
        run: |
          cd security-agent/terraform
          terraform plan -var-file=prod.tfvars -out=tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Post Plan Comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const plan = `${{ steps.plan.outputs.stdout }}`;
            github.rest.issues.createComment({
              issue_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## Terraform Plan\n\n```\n' + plan + '\n```'
            })
